version: "3.8"

services:
  postgres:
    image: postgres:15.5
    restart: always
    container_name: BD_prueba
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ejemplo
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
